export const artisanSkills = [
    { id: 'air_conditioning_installers', label: 'Air-Conditioning Installers' },
    { id: 'bakery_pastry_chef', label: 'Bakery / Pastry Chef' },
    { id: 'barbers', label: 'Barbers' },
    { id: 'bead_making', label: 'Bead Making' },
    { id: 'borehole_drillers', label: 'Borehole Drillers' },
    { id: 'candle_making', label: 'Candle Making' },
    { id: 'carpenter', label: 'Carpenter' },
    { id: 'computer_technicians', label: 'Computer Technicians' },
    { id: 'decoration', label: 'Decoration' },
    { id: 'dj_music_entertainment', label: 'DJ / Music Entertainment' },
    { id: 'drivers_chauffeurs', label: 'Drivers / Chauffeurs' },
    { id: 'electrician', label: 'Electrician' },
    { id: 'event_mc', label: 'Event MC' },
    { id: 'event_planners', label: 'Event Planners' },
    { id: 'flooring_specialists', label: 'Flooring Specialists (Marble / Vinyl / Laminate)' },
    { id: 'food_vendors_catering', label: 'Food Vendors / Catering Services' },
    { id: 'furniture_maker_upholsterer', label: 'Furniture Maker / Upholsterer' },
    { id: 'glass_mirror_installers', label: 'Glass / Mirror Installers' },
    { id: 'graphics_designer', label: 'Graphics Designer' },
    { id: 'hairdressing', label: 'Hairdressing' },
    { id: 'interior_designers', label: 'Interior Designers' },
    { id: 'landscape_designers', label: 'Landscape Designers' },
    { id: 'leather_work_bag_making', label: 'Leather Work / Bag Making' },
    { id: 'locksmiths', label: 'Locksmiths' },
    { id: 'makeup_artistry', label: 'Makeup Artistry' },
    { id: 'mason', label: 'Mason' },
    { id: 'mechanic', label: 'Mechanic' },
    { id: 'motorcycle_bicycle_repairers', label: 'Motorcycle / Bicycle Repairers' },
    { id: 'multi_tv_dstv_installers', label: 'Multi TV / DStv Installers' },
    { id: 'painter', label: 'Painter' },
    { id: 'pest_control_experts', label: 'Pest Control Experts' },
    { id: 'phone_repairers', label: 'Phone Repairers' },
    { id: 'photography_videography', label: 'Photography / Videography' },
    { id: 'plaster_false_ceiling_installers', label: 'Plaster / False Ceiling Installers' },
    { id: 'plumber', label: 'Plumber' },
    { id: 'printer_repairers', label: 'Printer Repairers' },
    { id: 'printing_publishing', label: 'Printing & Publishing' },
    { id: 'radio_presenter', label: 'Radio Presenter' },
    { id: 'security_system_installers', label: 'Security System Installers' },
    { id: 'sewing_embroidery', label: 'Sewing & Embroidery' },
    { id: 'shoe_making_cobbler', label: 'Shoe Making / Cobbler' },
    { id: 'soap_cosmetics_making', label: 'Soap / Cosmetics Making' },
    { id: 'solar_panel_installers', label: 'Solar Panel Installers' },
    { id: 'tailor', label: 'Tailor' },
    { id: 'tailoring_fashion_design', label: 'Tailoring & Fashion Design' },
    { id: 'tiler', label: 'Tiler' },
    { id: 'tv_decoder_repairers', label: 'TV & Decoder Repairers' },
    { id: 'welder', label: 'Welder' },
    { id: 'welding_fabrication', label: 'Welding & Fabrication' },
    { id: 'other', label: 'Other' },
];
