<?php

return [
    'skills' => [
        'air_conditioning_installers' => 'Air-Conditioning Installers',
        'bakery_pastry_chef' => 'Bakery / Pastry Chef',
        'barbers' => 'Barbers',
        'bead_making' => 'Bead Making',
        'borehole_drillers' => 'Borehole Drillers',
        'candle_making' => 'Candle Making',
        'carpenter' => 'Carpenter',
        'computer_technicians' => 'Computer Technicians',
        'decoration' => 'Decoration',
        'dj_music_entertainment' => 'DJ / Music Entertainment',
        'drivers_chauffeurs' => 'Drivers / Chauffeurs',
        'electrician' => 'Electrician',
        'event_mc' => 'Event MC',
        'event_planners' => 'Event Planners',
        'flooring_specialists' => 'Flooring Specialists (Marble / Vinyl / Laminate)',
        'food_vendors_catering' => 'Food Vendors / Catering Services',
        'furniture_maker_upholsterer' => 'Furniture Maker / Upholsterer',
        'glass_mirror_installers' => 'Glass / Mirror Installers',
        'graphics_designer' => 'Graphics Designer',
        'hairdressing' => 'Hairdressing',
        'interior_designers' => 'Interior Designers',
        'landscape_designers' => 'Landscape Designers',
        'leather_work_bag_making' => 'Leather Work / Bag Making',
        'locksmiths' => 'Locksmiths',
        'makeup_artistry' => 'Makeup Artistry',
        'mason' => 'Mason',
        'mechanic' => 'Mechanic',
        'motorcycle_bicycle_repairers' => 'Motorcycle / Bicycle Repairers',
        'multi_tv_dstv_installers' => 'Multi TV / DStv Installers',
        'painter' => 'Painter',
        'pest_control_experts' => 'Pest Control Experts',
        'phone_repairers' => 'Phone Repairers',
        'photography_videography' => 'Photography / Videography',
        'plaster_false_ceiling_installers' => 'Plaster / False Ceiling Installers',
        'plumber' => 'Plumber',
        'printer_repairers' => 'Printer Repairers',
        'printing_publishing' => 'Printing & Publishing',
        'radio_presenter' => 'Radio Presenter',
        'security_system_installers' => 'Security System Installers',
        'sewing_embroidery' => 'Sewing & Embroidery',
        'shoe_making_cobbler' => 'Shoe Making / Cobbler',
        'soap_cosmetics_making' => 'Soap / Cosmetics Making',
        'solar_panel_installers' => 'Solar Panel Installers',
        'tailor' => 'Tailor',
        'tailoring_fashion_design' => 'Tailoring & Fashion Design',
        'tiler' => 'Tiler',
        'tv_decoder_repairers' => 'TV & Decoder Repairers',
        'welder' => 'Welder',
        'welding_fabrication' => 'Welding & Fabrication',
        'other' => 'Other',
    ],
];
