<?php

return [
    'categories' => [
        'construction_trades' => [
            'label' => 'Construction & Skilled Trades',
            'sub_roles' => [
                'mason_block_layer' => 'Mason / Block Layer',
                'carpenter_joiner' => 'Carpenter / Joiner',
                'plumber' => 'Plumber',
                'steel_bender' => 'Steel Bender',
                'tiler' => 'Tiler',
                'painter' => 'Painter',
                'welder_fabricator' => 'Welder / Fabricator',
                'roofer' => 'Roofer',
                'pop_ceiling_installer' => 'POP Ceiling Installer',
                'scaffolding_technician' => 'Scaffolding Technician',
                'building_foreman' => 'Building Foreman',
                'site_supervisor' => 'Site Supervisor',
                'quantity_survey_assistant' => 'Quantity Survey Assistant',
            ],
        ],
        'home_maintenance' => [
            'label' => 'Home, Domestic & Maintenance Services',
            'sub_roles' => [
                'house_cleaner' => 'House Cleaner',
                'laundry_ironing' => 'Laundry & Ironing Services',
                'cook_home_chef' => 'Cook / Home Chef',
                'nanny_babysitter' => 'Nanny / Babysitter',
                'caregiver' => 'Caregiver',
                'house_help_domestic' => 'House Help / Domestic Worker',
                'pest_control' => 'Pest Control Services',
                'sofa_carpet_cleaning' => 'Sofa & Carpet Cleaning',
                'waste_collection' => 'Waste Collection Services',
                'house_maintenance_tech' => 'House Maintenance Technician',
            ],
        ],
        'automotive_mechanical' => [
            'label' => 'Automotive & Mechanical Services',
            'sub_roles' => [
                'auto_mechanic' => 'Auto Mechanic',
                'sprayer_panel_beater' => 'Sprayer / Panel Beater',
                'auto_electrician' => 'Auto Electrician',
                'car_ac_tech' => 'Car AC Technician',
                'motorcycle_repairer' => 'Motorcycle Repairer',
                'vulcanizer_tire_tech' => 'Vulcanizer / Tire Technician',
                'diesel_engine_mechanic' => 'Diesel Engine Mechanic',
                'vehicle_diagnostics' => 'Vehicle Diagnostics Technician',
                'spare_parts_dealer' => 'Spare Parts Dealer',
            ],
        ],
        'transport_logistics' => [
            'label' => 'Transport, Logistics & Heavy Equipment',
            'sub_roles' => [
                'driver_private_commercial' => 'Driver (Private / Commercial)',
                'truck_driver' => 'Truck Driver',
                'taxi_ride_hailing' => 'Taxi / Ride-Hailing Driver',
                'forklift_operator' => 'Forklift Operator',
                'excavator_operator' => 'Excavator Operator',
                'grader_operator' => 'Grader Operator',
                'roller_operator' => 'Roller Operator',
                'crane_operator' => 'Crane Operator',
                'dispatch_rider' => 'Dispatch Rider',
                'logistics_assistant' => 'Logistics Assistant',
            ],
        ],
        'electrical_electronics' => [
            'label' => 'Electrical & Electronics',
            'sub_roles' => [
                'electrician' => 'Electrician',
                'electrical_technician' => 'Electrical Technician',
                'cctv_installer' => 'CCTV Installer',
                'solar_panel_installer' => 'Solar Panel Installer',
                'inverter_technician' => 'Inverter Technician',
                'generator_technician' => 'Generator Technician',
                'appliance_repair_tech' => 'Appliance Repair Technician',
                'fire_alarm_installer' => 'Fire Alarm Installer',
                'access_control_tech' => 'Access Control Technician',
            ],
        ],
        'ict_digital' => [
            'label' => 'ICT & Digital Services',
            'sub_roles' => [
                'computer_repair_tech' => 'Computer Repair Technician',
                'network_technician' => 'Network Technician',
                'software_developer' => 'Software Developer',
                'website_designer' => 'Website Designer',
                'mobile_app_developer' => 'Mobile App Developer',
                'digital_marketer' => 'Digital Marketer',
                'social_media_manager' => 'Social Media Manager',
                'data_entry_officer' => 'Data Entry Officer',
                'it_support_officer' => 'IT Support Officer',
                'cyber_cafe_operator' => 'Cyber Café Operator',
            ],
        ],
        'business_office' => [
            'label' => 'Business, Office & Administration',
            'sub_roles' => [
                'secretary' => 'Secretary',
                'office_assistant' => 'Office Assistant',
                'admin_officer' => 'Administrative Officer',
                'receptionist' => 'Receptionist',
                'sales_executive' => 'Sales Executive',
                'marketing_officer' => 'Marketing Officer',
                'customer_service' => 'Customer Service Agent',
                'accountant_clerk' => 'Accountant / Accounts Clerk',
                'cashier' => 'Cashier',
                'hr_assistant' => 'Human Resource Assistant',
            ],
        ],
        'education_training' => [
            'label' => 'Education & Training',
            'sub_roles' => [
                'private_tutor' => 'Private Tutor',
                'classroom_teacher' => 'Classroom Teacher',
                'nursery_kindergarten_teacher' => 'Nursery / Kindergarten Teacher',
                'teaching_assistant' => 'Teaching Assistant',
                'school_administrator' => 'School Administrator',
                'ict_instructor' => 'ICT Instructor',
                'vocational_trainer' => 'Vocational Trainer',
                'adult_education_facilitator' => 'Adult Education Facilitator',
                'exam_invigilator' => 'Exam Invigilator',
            ],
        ],
        'health_care' => [
            'label' => 'Health & Social Care',
            'sub_roles' => [
                'nurse_assistant' => 'Nurse Assistant',
                'health_care_assistant' => 'Health Care Assistant',
                'community_health_worker' => 'Community Health Worker',
                'midwife_assistant' => 'Midwife Assistant',
                'laboratory_assistant' => 'Laboratory Assistant',
                'pharmacy_assistant' => 'Pharmacy Assistant',
                'elderly_caregiver' => 'Elderly Caregiver',
                'disability_support_worker' => 'Disability Support Worker',
                'first_aid_officer' => 'First Aid Officer',
            ],
        ],
        'hospitality_events' => [
            'label' => 'Hospitality, Events & Tourism',
            'sub_roles' => [
                'hotel_receptionist' => 'Hotel Receptionist',
                'cook_chef' => 'Cook / Chef',
                'kitchen_assistant' => 'Kitchen Assistant',
                'waiter_waitress' => 'Waiter / Waitress',
                'bartender' => 'Bartender',
                'event_usher' => 'Event Usher',
                'event_planner' => 'Event Planner',
                'decorator' => 'Decorator',
                'sound_system_tech' => 'Sound System Technician',
                'mc_event_host' => 'MC / Event Host',
            ],
        ],
        'fashion_beauty' => [
            'label' => 'Fashion & Beauty',
            'sub_roles' => [
                'fashion_designer' => 'Fashion Designer',
                'seamstress_tailor' => 'Seamstress / Tailor',
                'barber' => 'Barber',
                'hair_stylist' => 'Hair Stylist',
                'makeup_artist' => 'Makeup Artist',
                'nail_technician' => 'Nail Technician',
                'beautician' => 'Beautician',
                'fashion_illustrator' => 'Fashion Illustrator',
                'clothing_sales_assistant' => 'Clothing Sales Assistant',
            ],
        ],
        'agriculture' => [
            'label' => 'Agriculture & Agribusiness',
            'sub_roles' => [
                'farmer' => 'Farmer',
                'farm_labourer' => 'Farm Labourer',
                'poultry_attendant' => 'Poultry Attendant',
                'livestock_attendant' => 'Livestock Attendant',
                'fish_farmer' => 'Fish Farmer',
                'tractor_operator' => 'Tractor Operator',
                'agribusiness_assistant' => 'Agribusiness Assistant',
                'irrigation_technician' => 'Irrigation Technician',
                'crop_spray_tech' => 'Crop Spray Technician',
            ],
        ],
        'security' => [
            'label' => 'Security & Safety Services',
            'sub_roles' => [
                'security_guard' => 'Security Guard',
                'night_watchman' => 'Night Watchman',
                'bouncer' => 'Bouncer',
                'cctv_monitoring_officer' => 'CCTV Monitoring Officer',
                'security_supervisor' => 'Security Supervisor',
                'event_security_personnel' => 'Event Security Personnel',
                'access_control_officer' => 'Access Control Officer',
                'fire_safety_officer' => 'Fire Safety Officer',
            ],
        ],
        'media_creative' => [
            'label' => 'Media, Creative & Printing',
            'sub_roles' => [
                'photographer' => 'Photographer',
                'videographer' => 'Videographer',
                'graphic_designer' => 'Graphic Designer',
                'video_editor' => 'Video Editor',
                'content_creator' => 'Content Creator',
                'journalist_reporter' => 'Journalist / Reporter',
                'radio_presenter' => 'Radio Presenter',
                'voice_over_artist' => 'Voice-Over Artist',
                'animator' => 'Animator',
                'printing_technician' => 'Printing Technician',
            ],
        ],
        'general_jobs' => [
            'label' => 'General Jobs & Others',
            'sub_roles' => [
                'casual_worker' => 'Casual Worker',
                'general_labourer' => 'General Labourer',
                'cleaner' => 'Cleaner',
                'loader_offloader' => 'Loader / Offloader',
                'warehouse_assistant' => 'Warehouse Assistant',
                'shop_attendant' => 'Shop Attendant',
                'errand_runner' => 'Errand Runner',
                'field_worker' => 'Field Worker',
                'intern_apprentice' => 'Intern / Apprentice',
                'other' => 'Other',
            ],
        ],
    ],
];
